# Generated by Django 4.0.1 on 2022-06-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_img_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='img_src',
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
